export type KernelOp = {
  id: string;
  group: string;
  module: string;
  title: string;
  kernels: string[];
  grid: string;
  input: string;
  tile: string;
  load: string;
  compute: string;
  store: string;
  torch: string;
};

export const KERNEL_GROUPS = ["全部", "Activation", "Attention", "Indexer", "Norm / RoPE", "FLA / KDA", "Mamba / Cache", "MoE / Sample"];

export const KERNEL_OPS: KernelOp[] = [
  { id:"situ", group:"Activation", module:"activation/situ.py", title:"SiTU / SiTU×Up / Quant", kernels:["_situ_kernel","_situ_and_mul_kernel","_situ_and_mul_quant_kernel"], grid:"persistent (num_vector_cores,)", input:"x=[rows,2D]；可选 group_list", tile:"一行 gate[D] + up[D]，分块版用 BLOCK_H", load:"按 row 搬入 gate 与 up 两半；group_list 决定有效行", compute:"SiTU(g)=β·tanh(g/β)·sigmoid(g)；可乘 up，并为量化归约 absmax", store:"写 fp/bf16 输出，或 int8 输出与逐行 scale", torch:"gate=β*tanh(gate/β)*sigmoid(gate); out=gate*up" },
  { id:"swiglu_oai", group:"Activation", module:"activation/swiglu_oai.py", title:"SwiGLU OAI", kernels:["swiglu_oai_kernel"], grid:"(ceil(BS/BLOCK_SIZE),)", input:"hidden_states=[BS,2D]", tile:"MINIBLOCK_SIZE=16 行 × D 列", load:"从输入的两半搬入 gate 与 up", compute:"clamp → sigmoid(gate·α) → gate·sigmoid·(up+1)", store:"写 gated_output=[BS,D]", torch:"clamp(gate)*sigmoid(clamp(gate)*alpha)*(clamp(up)+1)" },
  { id:"swiglu_oai_q", group:"Activation", module:"activation/swiglu_oai_quant.py", title:"SwiGLU OAI Quant", kernels:["_swiglu_oai_quant_kernel"], grid:"persistent (num_vectorcore,)", input:"x=[rows,2D]；group_list；alpha；limit", tile:"一行 2D 输入，D 输出", load:"搬 gate/up；按 expert group 还原总行数", compute:"OAI SwiGLU 后 reduce absmax；scale=max(|out|)/dtype_max", store:"写量化 out 和每行 scale", torch:"out=...; scale=out.abs().amax(-1)/127; q=round(out/scale)" },
  { id:"swiglu_q", group:"Activation", module:"activation/swiglu_quant.py", title:"SwiGLU Quant", kernels:["_swiglu_quant_kernel"], grid:"persistent (num_vectorcore,)", input:"x=[rows,2D]；可选 expert group", tile:"一行 gate[D] + up[D]", load:"加载两半向量并转 fp32", compute:"gate·sigmoid(gate)·up；可 clamp up；求逐行 absmax", store:"写量化输出与 scale", torch:"F.silu(x[...,0::2])*x[...,1::2] → per-row quant" },

  { id:"decode_attn", group:"Attention", module:"attention/decode_attention.py", title:"Paged Decode MLA / GQA", kernels:["_paged_mla_fwd_kernel","_paged_gqa_fwd_kernel","_paged_gqa_fwd_kernel_high_performance"], grid:"(batch,kv_head) 或分离 QK/PV grid", input:"Q；paged K/V cache；block_table；seq_lens", tile:"Q heads×D 与一页 K/V[PAGE,D]", load:"先取 Q，再用 block_table 把逻辑页映射到物理 K/V 页", compute:"QKᵀ·scale；在线 max/sumexp Softmax；P·V 累加", store:"归一化 accumulator 写 Att_Out", torch:"scaled_dot_product_attention(Q,gather(K),gather(V))" },
  { id:"fia_prep", group:"Attention", module:"attention/fia_blockq_attention.py", title:"FIA Block‑Q 稀疏准备", kernels:["_fia_prep_kernel"], grid:"(total_q,)", input:"topk logical blocks；seq_lens；request→token 表", tile:"一个 query 的 TOPK1 block id", load:"读取 topk、request id 和当前 causal 长度", compute:"过滤 -1、排除 own block、cumsum 压紧，再映射到物理页", store:"写 block_table[query] 与 actual_kvlen", torch:"valid=topk[topk>=0]; physical=req_to_token[req,valid*BLOCK]" },
  { id:"gqa_sparse", group:"Attention", module:"attention/gqa_share_sparse_attention.py", title:"GQA Shared Sparse Decode", kernels:["_gqa_share_sparse_decode_bnsd_kernel","_merge_topk_attn_out_bnsd_kernel"], grid:"(chunk,batch,kv_head) → (batch,q_head)", input:"Q；sink；paged K/V；Top‑K block idx", tile:"一个 Top‑K chunk 的若干页×D", load:"按 topk idx 与页表搬稀疏 K/V；可同时加载 sink", compute:"每 chunk 在线 Softmax+PV；跨 chunk 用 LSE 权重合并", store:"临时 O/LSE，再写最终 out[B,QH,D]", torch:"对选中的 KV blocks 做 attention，再 logsumexp 合并 chunks" },
  { id:"sinks", group:"Attention", module:"attention/sinks_attention.py", title:"Attention Sinks Decode / Prefill", kernels:["attention_sinks_kernel","attention_sinks_prefill_kernel"], grid:"decode [S,head_group]；prefill [B,QH]", input:"Q；paged K/V；sink logits；sliding window", tile:"一个 query/head group × 一页 KV", load:"加载 sink 与 Q；遍历 block_table 搬入 K/V 页", compute:"sink 初始化 Softmax 状态；窗口内逐页在线 Softmax 与 P·V", store:"写 attn_out", torch:"softmax(cat([sink_score,QKᵀ])) 的 KV 概率乘 V" },

  { id:"index_prefill", group:"Indexer", module:"indexer/flash_block_score_prefill.py", title:"Flash Block Score Prefill", kernels:["_prefill_bnsd_score_kernel","_prefill_bnsd_score_attn_kernel","_prefill_topk_from_score_kernel"], grid:"Q-block×head×score-chunk → query×head", input:"Q；paged K/V；Q-block mappings；seq_lens", tile:"Q block×K block×D", load:"用 Q-block 映射和 block_table 搬 Q、K；融合版同时搬 V", compute:"QK 分数按 block 聚合；可附带 attention；最后 Top‑K 并补 local block", store:"score / index attention output / topk block ids", torch:"scores=einsum(Q,K); block_score=reduce(scores); topk(block_score)" },
  { id:"index_decode", group:"Indexer", module:"indexer/flash_block_score_decode.py", title:"Flash Block Score Decode", kernels:["_merge_bnsd_score_topk_candidates_kernel","_merge_bnsd_score_topk_candidates_impl","_merge_bnsd_score_topk_candidates_guarded_kernel","_merge_topk_append_local_impl","_merge_topk_append_local_kernel","_decode_bnsd_score_topk_chunk_kernel","_decode_bnsd_score_attn_chunk_kernel","_merge_bnsd_attn_out_kernel","_native_sanitize_topk_kernel","_append_local_block_to_topk_idx_kernel"], grid:"score chunks 并行 → (batch,head) 合并", input:"Q；paged K/V；seq_lens；block mapping", tile:"一批候选 KV blocks 与 topk 槽位", load:"每个 chunk 搬 Q 与它负责的 K/V blocks", compute:"局部 score/topk/attention → 全局候选合并 → 清理越界 → 追加 local block → LSE 合并", store:"写 topk_idx 与可选 attention out", torch:"chunked topk(QK scores) → global topk；selected attention" },

  { id:"chunk_h", group:"FLA / KDA", module:"fla/chunk_delta_h.py", title:"Gated Delta Rule · State H", kernels:["chunk_gated_delta_rule_fwd_kernel_h_blockdim64_npu_kernel"], grid:"V blocks × sequence/head chunks", input:"K,V,W,g,H0；chunk offsets", tile:"BT×K、BT×V 与 K×V state", load:"按 chunk 取初始 state、W/K/V 与 gate", compute:"v_new=V−W·H；H←decay(H)+Kᵀ·v_new", store:"写 v_new、每 chunk H 与可选 final state", torch:"v_new=v-w@h; h=decay*h+k.T@v_new" },
  { id:"chunk_o", group:"FLA / KDA", module:"fla/chunk_o.py", title:"Gated Delta Rule · Output O", kernels:["chunk_fwd_kernel_o_npu_kernel"], grid:"chunk×head×V-block", input:"Q,K,V,H,g", tile:"BT×K、K×V、BT×V", load:"按 chunk 搬 Q/K/H/g/V", compute:"O=Q·H；A=causal(Q·Kᵀ)；gate 缩放；O=(O+A·V)·scale", store:"写 O chunk", torch:"(q@h + tril(q@k.T)@v)*scale" },
  { id:"scaled_kkt", group:"FLA / KDA", module:"fla/chunk_scaled_dot_kkt.py", title:"Chunk Scaled K·Kᵀ", kernels:["chunk_scaled_dot_kkt_fwd_trans_kernel"], grid:"(num_chunks,1)", input:"K；beta；g_cumsum", tile:"K[BT,BK] → A[BT,BT]", load:"搬 K chunk、beta 与 gate 累积", compute:"A=(K·Kᵀ)·beta；加入 gate scaling；应用严格下三角 mask", store:"写 A chunk", torch:"torch.tril((K@K.T)*beta,diagonal=-1)" },
  { id:"cumsum", group:"FLA / KDA", module:"fla/cumsum.py", title:"Chunk Local Cumsum", kernels:["chunk_local_cumsum_scalar_kernel"], grid:"(num_blocks,B)", input:"s=[B,H,T] 或 [B,T,H]", tile:"BLOCK_T 时间元素", load:"按 chunk_indices 与 varlen 边界搬 s", compute:"tl.cumsum；可 reverse；可乘 scale", store:"写同形 o", torch:"torch.cumsum(s,dim=time)" },
  { id:"gdn_gate", group:"FLA / KDA", module:"fla/fused_gdn_gating.py", title:"Fused GDN Gating", kernels:["fused_gdn_gating_kernel","fused_gdn_gating_kernel_without_sigmoid_kernel"], grid:"batch/head blocks × seq_len", input:"A_log,a,b,dt_bias", tile:"batch block×head block 的一个时间步", load:"搬 A_log、a、bias 与可选 b", compute:"softplus(a+bias)；g=−exp(A_log)·softplus；可算 sigmoid(b)", store:"写 g 与 beta_output", torch:"g=-A_log.exp()*F.softplus(a+dt_bias); beta=sigmoid(b)" },
  { id:"recurrent", group:"FLA / KDA", module:"fla/fused_sigmoid_gating_recurrent.py", title:"Sigmoid Gating Recurrent", kernels:["fused_sigmoid_gating_delta_rule_update_npu_kernel"], grid:"(V-block,sequence,head)", input:"Q,K,V,b,A_log,a,dt_bias,H0", tile:"K×V state + 单 token Q/K/V", load:"读取或初始化 H；逐 token 搬 Q/K/V 与 gates", compute:"衰减 H；delta update；O=HᵀQ；状态递推", store:"写 O 与更新后的 H0", torch:"for t: H=decay*H+k⊗(v-H.T@k); o=H.T@q" },
  { id:"kda_h", group:"FLA / KDA", module:"fla/kda_chunk_delta_h.py", title:"KDA Chunk State H", kernels:["chunk_gated_delta_rule_fwd_kernel_h_npu"], grid:"(ceil(V/32),N×H)", input:"K,V,W,g,gk,initial_state", tile:"BT×K、BT×V、K×V state", load:"按变长序列 chunk 搬初态与 K/V/W/g/gk", compute:"W·H 修正 V；gate 衰减；Kᵀ·V 更新两段 state", store:"写 v_new、chunk state 与 final state", torch:"KDA chunk recurrence（矩阵化 delta update）" },
  { id:"kda_gate", group:"FLA / KDA", module:"fla/kda_gate.py", title:"KDA Gate", kernels:["_kda_gate_fwd_kernel"], grid:"(ceil(T/BT),H)", input:"g,A,g_bias", tile:"BT token × D gate", load:"搬 gate、每 head A 与可选 bias", compute:"softplus 或 lower_bound·sigmoid 分支", store:"写 y[T,H,D]", torch:"softplus(g+bias) 或 lower_bound*sigmoid(exp(A)*(g+bias))" },
  { id:"kda_prefill", group:"FLA / KDA", module:"fla/kda_prefill.py", title:"KDA Prefill W/U + O", kernels:["_recompute_w_u_fwd_kernel","_chunk_gla_fwd_kernel_o"], grid:"chunk×head×K/V blocks", input:"K,V,beta,A,gk,Q,g,H", tile:"BT×K、BT×V、BT×BT", load:"按 chunk 搬 A、K、V、beta/gates、Q/H", compute:"U=A·(beta·V)，W=A·(gated K)；O=Q·H+causal(QKᵀ)·V", store:"写 W、U 与 O", torch:"u=A@(beta*v); w=A@k_gated; o=q@h+tril(q@k.T)@v" },
  { id:"kda_verify", group:"FLA / KDA", module:"fla/kda_target_verify.py", title:"KDA Target Verify", kernels:["_kda_target_verify_kernel"], grid:"request/head/V blocks", input:"Q,K,V,gates；initial/snapshot state", tile:"草稿 token 序列 × K×V state", load:"按 request 索引搬初态或 snapshot 与草稿 Q/K/V", compute:"逐草稿 token 重放 KDA recurrence，生成 target output", store:"写验证输出与 snapshot", torch:"逐 token 参考循环重放 state update" },
  { id:"l2", group:"FLA / KDA", module:"fla/l2norm.py", title:"L2Norm", kernels:["l2norm_fwd_kernel1","l2norm_fwd_kernel_opt"], grid:"rows 或 persistent token blocks", input:"x[...,D]", tile:"一行或 BT×D", load:"按尾部维搬 x 并转 fp32", compute:"denom=sqrt(sum(x²))+eps；y=x/denom", store:"写同形 y", torch:"F.normalize(x,p=2,dim=-1,eps=eps)" },
  { id:"ln_gate", group:"FLA / KDA", module:"fla/layernorm_gated.py", title:"Layer/RMSNorm + Gate", kernels:["_layer_norm_fwd_1pass_kernel_npu_simd","_layer_norm_fwd_1pass_kernel_npu"], grid:"rows 或 M/N tiles", input:"X,W,B；可选 Z gate", tile:"一行 N 或 BLOCK_M×BLOCK_N", load:"搬 X/W/B/Z", compute:"LayerNorm 或 RMSNorm；affine；可在 norm 前或后乘 SiLU(Z)", store:"写 Y、Mean、Rstd", torch:"norm(x)*w+b；可乘 F.silu(z)" },
  { id:"solve", group:"FLA / KDA", module:"fla/solve_tril.py", title:"Solve Lower‑Triangular", kernels:["solve_tril_16x16_kernel_paral","solve_tril_16x16_kernel_paral_v3","merge_16x16_to_32x32_inverse_kernel","merge_16x16_to_64x64_inverse_kernel_reorder_all_masked","merge_16x16_to_64x64_inverse_kernel"], grid:"chunk×head×sub-block", input:"下三角 A[BT,BT]", tile:"16×16 基块，再合并 32×32/64×64", load:"先搬对角 16×16 块", compute:"块内三角逆；利用块矩阵公式逐级合并更大逆矩阵", store:"写 Ad/Ai 分级中间量与最终逆", torch:"torch.linalg.solve_triangular(A,I,upper=False)" },
  { id:"qkvcat", group:"FLA / KDA", module:"fla/utils.py", title:"QKVZBA Split / Reshape / Cat", kernels:["safe_exp","fused_qkvzba_split_reshape_cat_kernel","fused_qkvzba_split_reshape_cat_contiguous_kernel"], grid:"persistent row/vector blocks", input:"mixed_qkv,z,b,a", tile:"ROWS_PER_ITER×列块", load:"按各输出列边界搬 mixed tensors", compute:"索引拆分、reshape 与拼接；safe_exp 是内部稳定指数 helper", store:"写 mixed_qkvz 与 mixed_ba", torch:"cat([reshape(qkv),z],-1), cat([b,a],-1)" },
  { id:"wy", group:"FLA / KDA", module:"fla/wy_fast.py", title:"WY Fast Recompute W/U", kernels:["recompute_w_u_fwd_kernel_npu_kernel"], grid:"chunk×head×K/V blocks", input:"K,V,beta,A,g", tile:"BT×K、BT×V、BT×BT", load:"搬 A/K/V/beta/g chunk", compute:"构造 gated K；W=A·K；U=A·(beta·V)", store:"写 W 与 U", torch:"w=A@k_gated; u=A@(beta*v)" },

  { id:"mix", group:"Mamba / Cache", module:"kimi_k3/attn_residual.py", title:"Kimi K3 Attention Residual Mix", kernels:["_mix_fused_kernel"], grid:"persistent num_vector_cores", input:"prefix tokens；bank；candidate weights", tile:"一个输出 token 的候选行 × hidden block", load:"搬候选 scores/weights 与对应 prefix/bank value", compute:"Softmax candidates；按概率加权 hidden vectors", store:"写混合后的 out[token,H]", torch:"out=(softmax(scores)[...,None]*values).sum(candidate)" },
  { id:"conv", group:"Mamba / Cache", module:"mamba/causal_conv1d.py", title:"Causal Conv1D Update", kernels:["_causal_conv1d_update_kernel_npu_tiled","_causal_conv1d_update_kernel_no_cache_len_no_mtp","_causal_conv1d_update_kernel"], grid:"batch tile × channel tile；tiled 版本每个 program 内遍历 B_TILE 个序列", input:"x=[batch,seqlen,dim] 或 varlen [num_tokens,dim]；conv_state=[cache_lines,dim,state_len]；weight=[width,dim]；bias；cache/APC/spec indices", tile:"B_TILE 个序列 × BLOCK_N channels；状态搬运按 T_CHUNK×BLOCK_N 分块", load:"一次预取 width≤6 的通道权重与 bias；按 cache line 搬历史窗口，并逐 token 搬 x", compute:"先滚动/覆盖 conv_state；每个 token 用 FP32 累加 depthwise dot 与 bias，再 RNE 下转 FP16，启用 SiLU 时重新转 FP32 计算激活", store:"分块写新 conv_state；写输出；旧路径可写 intermediate conv window", torch:"acc=sum(history.float()*weight.float())+bias.float(); out=acc.to(x.dtype); out=F.silu(out)；随后更新缓存" },
  { id:"conv_verify", group:"Mamba / Cache", module:"mamba/causal_conv1d_verify.py", title:"Causal Conv1D Spec Verify", kernels:["_causal_conv1d_linear_verify_kernel"], grid:"(batch,ceil(channels/block_c))", input:"draft x；state；weights；snapshot indices", tile:"channel block × 历史窗口", load:"搬 state、weight、bias；逐 draft step 搬 current", compute:"逐步卷积/激活并滚动 history，同时保存验证快照", store:"写 draft out、snapshot 与最终 state", torch:"for draft: window=roll(window); out=(window*w).sum()+b" },
  { id:"state_move", group:"Mamba / Cache", module:"mamba/mamba_state_update_triton.py", title:"Mamba State Move / Rollback", kernels:["move_cache_dynamic_last_kernel_h_block","move_cache_dynamic_last_kernel_h_block_kda","_conv_state_rollback_kernel"], grid:"request 或 cache-copy tasks", input:"src/dst cache；request/step indices", tile:"H_BLOCK×V×K 或 conv window", load:"由 src_idx、dst_idx、last_step 计算动态地址并搬块", compute:"索引重排；rollback 将 snapshot step 复制回正式状态", store:"写目标 recurrent/conv cache", torch:"dst[dst_idx]=src[src_idx,last_step]; state.copy_(snapshot)" },
  { id:"scatter", group:"Mamba / Cache", module:"mamba/speculative_state_scatter.py", title:"Speculative State Scatter", kernels:["_speculative_state_scatter_kernel"], grid:"persistent min(48,requests×layers×tail_tiles)", input:"src speculative states；dst states；request/step indices", tile:"一个 request/layer 的 tail block", load:"persistent task 解码 request、layer、tail tile 后搬 src step", compute:"纯地址映射与边界 mask", store:"scatter 到 dst request slot", torch:"dst[:,dst_idx]=src[:,src_idx,step_idx]" },
  { id:"alloc", group:"Mamba / Cache", module:"mem_cache/allocator.py", title:"Paged Cache Alloc Extend", kernels:["alloc_extend_kernel"], grid:"每 request 一个 program", input:"pre_len,seq_len,last_loc,free_pages", tile:"一个 request + 前方 requests 的长度向量", load:"搬 0..pid 的长度做前缀和，再搬 free page ids", compute:"算 extend_len、新增页数、独占 page 起点与 token→slot 地址", store:"写 out_indices 与连接后的页位置", torch:"pages=cumsum(ceil_div(extend,page)); out=page_id*page_size+offset" },
  { id:"kvstore", group:"Mamba / Cache", module:"mem_cache/kv_cache_store.py", title:"KV Cache Prefix‑Valid Store", kernels:["_store_kv_cache_prefix_valid_npu_kernel"], grid:"(batch,prefix_rows,ceil(max(K,V)/BLOCK))", input:"src K/V；loc；commit_lens", tile:"一个 src row 的 K/V 列块", load:"row<commit_len 时读取 loc，再搬 src K/V", compute:"用 loc 将源行映射到 cache 目标行", store:"写 dst_k[loc] 与 dst_v[loc]", torch:"dst_k[loc[valid]]=src_k[valid]; dst_v[loc[valid]]=src_v[valid]" },

  { id:"muladd", group:"MoE / Sample", module:"moe/mul_add.py", title:"MoE Mul‑Add", kernels:["mul_add_kernel"], grid:"persistent (min(batch_rows, num_vector_cores),)", input:"input1_ptr=routed hidden states [batch_rows, hidden_size]；input2_ptr=shared/residual hidden states [batch_rows, hidden_size]；factor 为 routed 分支缩放系数", tile:"每个 program 每轮处理一行 BLOCK_SIZE hidden", load:"按同一个 input_offsets 搬入 routed_values 与 shared_values；cols < hidden_size 保护尾部 lane", compute:"buffered_values = routed_values × factor + shared_values", store:"按 row_idx × hidden_size + cols 写 output_ptr", torch:"input1 * factor + input2" },
  { id:"zeroexpert", group:"MoE / Sample", module:"moe/zero_experts_compute_identity.py", title:"Zero‑Expert Identity", kernels:["experts_compute_identity_kernel"], grid:"[tokens]", input:"expert indices/scales；hidden_states", tile:"一个 token 的 K experts + D hidden", load:"搬 expert ids/scales，判断全部无效；必要时搬 hidden", compute:"无有效 expert 时构造 identity route；清零多余 scales", store:"写修正后的 route/scales 与 zero_result", torch:"if no_valid_expert: result=hidden; first_route=identity" },
  { id:"argmax", group:"MoE / Sample", module:"sample/argmax_softmax_prob.py", title:"Argmax + Softmax Probability", kernels:["_argmax_prob_kernel"], grid:"persistent min(cores,B)", input:"logits=[B,V]", tile:"BLOCK_V 词表元素", load:"一行词表分 tile 搬入；尾块补 -inf", compute:"跨 tile 在线维护 max、arg 与 sumexp", store:"写 argmax id 与最大 token 概率 1/s", torch:"arg=logits.argmax(-1); p=softmax(logits,-1).gather(-1,arg)" },
  { id:"chain_sample", group:"MoE / Sample", module:"sample/chain_speculative_sampling.py", title:"Chain Speculative Rejection Sampling", kernels:["_chain_rejection_accept_kernel","_chain_rejection_block_sum_kernel","_chain_rejection_sample_kernel"], grid:"三次 launch：(batch) → persistent min(batch×vocab_blocks, vector_cores) → (batch)", input:"candidates/retrive_index/uniform_samples=[B,num_draft]；target_probs=[B,num_draft,V]；draft_probs=[B,draft_rows,V]", tile:"接受阶段每个 program 处理一条 draft chain；归约阶段每轮处理一个 2048-token vocab block；采样阶段处理选中的一个 vocab block", load:"沿 chain 逐步读取 candidate、target/draft probability 与随机数；再分块加载 residual vocab probability", compute:"按 u·p_draft<p_target 依次接受，首次拒绝即停；计算 residual=max(p_target−p_draft,0)，跨 vocab block 做 CDF 并抽最终 token", store:"写 accept_index/accept_token_num/predicts；中间 metadata=[target row,output slot,all accepted] 与 block_sums", torch:"逐 draft 做 rejection sampling；最终从 normalize(relu(target_probs-draft_probs)) 抽样；全接受时从 target_probs 抽样" },
  { id:"tree_target", group:"MoE / Sample", module:"sample/tree_speculative_sampling_target_only.py", title:"Tree Speculative Sampling · Target Only", kernels:["_tree_target_only_accept_kernel","_tree_target_only_block_sum_kernel","_tree_target_only_sample_kernel"], grid:"三次 launch：(batch) → persistent min(batch×vocab_blocks, vector_cores) → (batch)", input:"tree candidates/retrive child+sibling/uniform=[B,num_draft]；target_probs=[B,num_draft,V]；draft_probs 作为 rejected scratch", tile:"接受阶段每 program 遍历一棵 request tree；归约/采样阶段以 2048 个 vocab token 为块", load:"按 depth 读取首 child 并沿 sibling 链读取 token、target probability 与 coin；最后加载 target−rejected 概率块", compute:"同一深度累积 sibling target probability，按 threshold_acc/threshold_single 接受；记录拒绝 sibling 概率；最终对 relu(target−rejected) 做分块 CDF 采样", store:"写 accepted path、accept_token_num、predicts、rejected scratch、metadata 与 block_sums", torch:"按 child/sibling 重放 target-only tree acceptance；最终 multinomial(relu(target_probs-rejected_probs))" },
  { id:"verifytree", group:"MoE / Sample", module:"sample/verify_tree_greedy.py", title:"Speculative Tree Greedy Verify", kernels:["verify_tree_greedy_kernel"], grid:"(batch_requests,)", input:"draft tree links；candidate tokens；target predictions", tile:"一个 request 的 pad_num_draft_tokens", load:"搬 candidates、retrieve indices、target token 与 child/sibling", compute:"从 root 逐级匹配 target，沿 child/sibling 接受路径", store:"写 accept_index、accept_token_num 与下一 predicts", torch:"每个 request 执行等价 while/tree traversal" },

  { id:"add_rms", group:"Norm / RoPE", module:"norm/add_rmsnorm_bias.py", title:"Add + RMSNorm + Bias / Gemma", kernels:["add_rmsnorm_bias_kernel","add_gemma_rms_norm_kernel"], grid:"rows 或 persistent cores", input:"input,residual,weight,bias；可选 quant params", tile:"一行 hidden_size", load:"搬 input、residual 与 norm affine 参数", compute:"残差相加 → RMS variance/rsqrt → 乘 weight 加 bias → 可选量化", store:"写 norm output 与可选 add_output", torch:"z=x+residual; y=F.rms_norm(z)*w+b" },
  { id:"rope", group:"Norm / RoPE", module:"norm/fused_rope_qk_mqa.py", title:"Fused RoPE Q/K MQA", kernels:["fused_rope_qk_mqa_kernel_opt"], grid:"(T,)", input:"Q,K；cos/sin cache", tile:"一个 token 的多个 Q/K heads × rope D", load:"加载当前 position 的 cos/sin 与 Q/K 偶奇维", compute:"even*cos−odd*sin；odd*cos+even*sin；非 rope 维直传", store:"写 rotated Q/K", torch:"apply_rotary_pos_emb(Q,K,cos,sin)" },
  { id:"splitqk", group:"Norm / RoPE", module:"norm/fused_split_qk_norm.py", title:"Split Q/K + RMSNorm", kernels:["fused_split_qk_norm_kernel"], grid:"(B,)", input:"fused=[B,q_lora+kv_lora+rope]；Q/K weights", tile:"一行三个连续区间", load:"按列区间拆 Q、K-nope、K-pe", compute:"Q/K 各自 RMSNorm+affine；K-pe 直传", store:"写三个独立输出", torch:"q,k,pe=torch.split(...); q=rms_norm(q); k=rms_norm(k)" },
  { id:"l1", group:"Norm / RoPE", module:"norm/l1_norm.py", title:"L1 Normalize", kernels:["l1_norm_kernel"], grid:"persistent num_vectorcore", input:"x=[rows,H]", tile:"一行 H", load:"每轮搬一个 row", compute:"按源码语义 y=x/sum(x)", store:"写同形 y", torch:"x / x.sum(-1,keepdim=True)" },
  { id:"rmsbias", group:"Norm / RoPE", module:"norm/rmsnorm_bias.py", title:"RMSNorm + Bias / Quant", kernels:["rmsnorm_bias_kernel"], grid:"(rows,)", input:"x,weight,bias；可选 quant scale/offset", tile:"一行 hidden_size", load:"搬 x 与 affine/quant 参数", compute:"RMSNorm → 乘 weight 加 bias → 可选 scale+offset 量化", store:"写 fp 或 int8 output", torch:"F.rms_norm(x)*weight+bias" },
  { id:"rmssplit", group:"Norm / RoPE", module:"norm/rmsnorm_split.py", title:"Split RMSNorm 两阶段", kernels:["fused_rsqrt_mul_kernel","fused_variance_kernel"], grid:"persistent (kernel_num,)，两次 launch", input:"x；weight；eps", tile:"BLOCK_L×hidden（variance）/ BLOCK_L×BLOCK_C（apply）", load:"阶段1搬整行 x；阶段2搬 x tile、variance 与 weight", compute:"阶段1 sum(x²)/C；阶段2 x·rsqrt(var+eps)·weight", store:"先写 variance，再写 output", torch:"var=x.square().mean(-1); out=x*rsqrt(var+eps)*w" },
  { id:"rms", group:"Norm / RoPE", module:"norm/rmsnorm_without_weight.py", title:"RMSNorm Without Weight", kernels:["fused_rmsnorm_without_weight_kernel"], grid:"persistent (num_vectorcore,)", input:"x=[tokens,H]；eps", tile:"BLOCK_L×H", load:"每轮搬若干 token 的完整 hidden", compute:"逐 token sum(x²)/H → rsqrt → x·rstd", store:"写同形 output", torch:"F.rms_norm(x,(H,),weight=None,eps=eps)" },
  { id:"scaleshift", group:"Norm / RoPE", module:"norm/scale_shift.py", title:"Scale + Shift", kernels:["fused_scale_shift_kernel","fused_scale_shift_kernel_2"], grid:"persistent (kernel_num,)", input:"x；标量/向量 scale；标量/张量 shift", tile:"BLOCK_L×BLOCK_C", load:"搬 x，并按广播类型加载 scale/shift", compute:"output=x·scale+shift", store:"写同形 output", torch:"x * scale + shift" },
  { id:"qkvmrope", group:"Norm / RoPE", module:"norm/split_qkv_rmsnorm_mrope.py", title:"Split QKV + RMSNorm + Multimodal RoPE", kernels:["split_qkv_rmsnorm_mrope_kernel"], grid:"persistent (block_dim=min(vector_cores,num_tokens),)；front/tail cores 分摊 token", input:"fused qkv(/gate)=[tokens,q_size+gate_size+2×kv_size]；Q/K norm weight+bias；T/H/W cos-sin=[3,tokens,rope_dim]", tile:"一个 program 每轮处理一个 token：Q[num_q_heads,head_size]、K/V[num_kv_heads,head_size] 与可选 gate", load:"权重每 program 只搬一次；每轮拆出 Q/gate/K/V，并按 mrope_section 从 temporal/height/width 三组表选择 cos/sin", compute:"Q/K 分 head 做 FP32 RMSNorm；构造 rotate_half；按 interleaved 或连续 T/H/W section 组合 cos/sin；支持 partial RoPE", store:"分别写 Q、K、V 与可选 gate；partial RoPE 保留未旋转尾维", torch:"split fused QKV → rms_norm(Q/K) → apply_multimodal_rotary_pos_emb(T/H/W sections) → Q,K,V,gate" },
  { id:"qkvrope", group:"Norm / RoPE", module:"norm/split_qkv_rmsnorm_rope.py", title:"Split QKV + RMSNorm + RoPE", kernels:["split_qkv_rmsnorm_rope_kernel","split_qkvgate_gemma_rmsnorm_rope_kernel"], grid:"(rows,column_groups,1)", input:"fused QKV(/gate)；sin/cos；Q/K weights", tile:"Q/K head blocks 与 V 列块", load:"从 fused 输入分段搬 Q、K、V、可选 gate；加载 RoPE 表", compute:"Q/K head-wise RMSNorm；RoPE 旋转；V/gate 直传", store:"写独立 Q,K,V 与可选 gate", torch:"split → rms_norm(Q/K) → apply_rope → outputs" },
  { id:"qkvhalf", group:"Norm / RoPE", module:"norm/split_qkv_rmsnorm_rope_pos_cache_half_npu.py", title:"Split QKV + Half Pos Cache RoPE", kernels:["fp32_to_bf16_rne","split_qkv_rmsnorm_rope_half_pos_cache_kernel"], grid:"(rows,column_groups,1)", input:"fused QKV；position ids；half cos/sin cache", tile:"一行 Q/K heads 与 V", load:"按 pos 取半宽 cos/sin；分段加载 Q/K/V", compute:"Q/K RMSNorm（确定性 BF16 RNE helper）+ half-layout RoPE", store:"写 Q,K,V", torch:"split + rms_norm + rotary using cache[pos]" },
  { id:"qkvtp", group:"Norm / RoPE", module:"norm/split_qkv_tp_rmsnorm_rope.py", title:"TP Split QKV + Global RMSNorm + RoPE", kernels:["_split_qkv_and_compute_local_qk_var_kernel","_apply_global_rmsnorm_kernel"], grid:"persistent min(batch,cores)，两次 launch", input:"TP shard fused QKV；all-reduced Q/K variance；RoPE", tile:"一行本地 Q/K/V shard", load:"阶段1 split 本地 Q/K/V；阶段2加载全局 variance 与 weights/sin/cos", compute:"本地 sumsq → 外部 TP all-reduce → global RMSNorm → RoPE", store:"写 Q/K/V 与 qk_var", torch:"split; dist.all_reduce(sum_sq); rms_norm_global; apply_rope" },
];

export const TOTAL_TRITON_KERNELS = KERNEL_OPS.reduce((sum, op) => sum + op.kernels.length, 0);
