#!/usr/bin/env python3
"""Generate compact Triton signatures used by Production Kernel Lab.

The source timeline generator keeps every executable statement.  This companion
index keeps only the function ABI and a few representative load/store/address
expressions so the Lab can classify every argument without importing Python at
runtime.
"""

from __future__ import annotations

import argparse
import ast
import json
import re
from pathlib import Path


def dotted_name(node: ast.AST) -> str | None:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        prefix = dotted_name(node.value)
        return f"{prefix}.{node.attr}" if prefix else node.attr
    return None


def is_triton_jit(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    for decorator in node.decorator_list:
        name = ast.unparse(decorator)
        if (
            name == "triton.jit"
            or name.startswith("triton.jit(")
            or name.endswith(".jit")
            or name == "jit"
        ):
            return True
    return False


def compact(source: str, node: ast.AST) -> str:
    segment = ast.get_source_segment(source, node) or ast.unparse(node)
    return " ".join(segment.split())


def referenced_args(expression: str, args: list[str]) -> list[str]:
    return [name for name in args if re.search(rf"\b{re.escape(name)}\b", expression)]


def signature(source: str, node: ast.FunctionDef | ast.AsyncFunctionDef) -> dict:
    args = [arg.arg for arg in node.args.args]
    calls: list[tuple[int, ast.Call, str]] = []
    for child in ast.walk(node):
        if not isinstance(child, ast.Call):
            continue
        name = dotted_name(child.func) or ""
        if name == "tl.load":
            calls.append((child.lineno, child, "load"))
        elif name == "tl.store" or name.startswith("tl.atomic_"):
            calls.append((child.lineno, child, "store"))
    calls.sort(key=lambda item: item[0])

    loads: list[str] = []
    stores: list[str] = []
    load_exprs: list[str] = []
    store_exprs: list[str] = []
    for _, call, kind in calls:
        expression = compact(source, call)
        target = loads if kind == "load" else stores
        for name in referenced_args(expression, args):
            if name not in target:
                target.append(name)
        expressions = load_exprs if kind == "load" else store_exprs
        if expression not in expressions and len(expressions) < 5:
            expressions.append(expression)

    compute_exprs: list[str] = []
    candidates = [
        item
        for item in ast.walk(node)
        if isinstance(item, (ast.Assign, ast.AnnAssign, ast.AugAssign))
    ]
    candidates.sort(key=lambda item: (item.lineno, item.col_offset))
    for item in candidates:
        expression = compact(source, item)
        if "tl.load(" in expression or "tl.store(" in expression or "tl.atomic_" in expression:
            continue
        if expression not in compute_exprs:
            compute_exprs.append(expression)
        if len(compute_exprs) == 5:
            break

    return {
        "args": args,
        "line": node.lineno,
        "loads": loads,
        "stores": stores,
        "loadExprs": load_exprs,
        "storeExprs": store_exprs,
        "computeExprs": compute_exprs,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    source_root = args.source_root.resolve()
    result: dict[str, dict[str, dict]] = {}
    for path in sorted(source_root.rglob("*.py")):
        source = path.read_text(encoding="utf-8")
        try:
            tree = ast.parse(source, filename=str(path))
        except SyntaxError as error:
            raise SystemExit(f"cannot parse {path}: {error}") from error
        module = path.relative_to(source_root).as_posix()
        for node in tree.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and is_triton_jit(node):
                result.setdefault(module, {})[node.name] = signature(source, node)

    output = (
        "// Generated by scripts/generate-kernel-signatures.py; do not edit by hand.\n"
        "export type KernelSignature = { args: string[]; line: number; loads: string[]; stores: string[]; loadExprs: string[]; storeExprs: string[]; computeExprs: string[] };\n"
        "export const KERNEL_SIGNATURES: Record<string, Record<string, KernelSignature>> = "
        + json.dumps(result, ensure_ascii=False, separators=(",", ":"))
        + ";\n"
    )
    args.output.write_text(output, encoding="utf-8")
    kernel_count = sum(len(kernels) for kernels in result.values())
    print(f"generated {kernel_count} Triton signatures in {args.output}")


if __name__ == "__main__":
    main()
